### ISSUE TITLE
Getting header error

### ISSUE THREAD

**Issue by denen99** [wulczer/tsung_ws#1]
I am using sockjs and getting the following error in tsung.log.  

=INFO REPORT==== 22-May-2012::12:06:39 ===
        ts_websocket:(5:<0.179.0>) WEBSOCKET: Header <<"Sec-WebSocket-Accept">> not found 

=INFO REPORT==== 22-May-2012::12:06:39 ===
        ts_websocket:(5:<0.179.0>) WEBSOCKET: Wrong accept header: [<<>>] 

However wireshark shows request is OK

GET /socket/websocket HTTP/1.1
Host: localhost
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 3SZltWK7EDuHpBdFuPF0CA==
Sec-WebSocket-Version: 13

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Sec-Websocket-Accept: WtkGIeXNwI16fImUje5+j7B6Mnw=
Connection: Upgrade

**Comment by wulczer** [comment]
It seems that the header that sockjs is sending is `Sec-Websocket-Accept` (note the lowercase `s` in `Websocket`).

This looks like a bug in tsung_ws, since as far as I remember header names are case insensitive. Will fix.

Thanks for the report!

**Comment by wulczer** [comment]
Fixed, thanks!
