### ISSUE TITLE
How can I use this tool to test my own server?

### ISSUE THREAD

**Issue by ashikcse** [wulczer/tsung_ws#5]
I want to use this tool to test my own server that is running on yaws instead of python server. Can you please help me with suggestion how can I use this tool to test my own?

Thanks,
Ashik

**Comment by wulczer** [comment]
Hi Ashik,

it's very similar to testing the example Python server, but depends on what data does your Erlang server expect. If your clients are not expected to send anything to the server, you can remove all `<websocket type="send">` elements from `websocket.xml` and use that as the basis of your config file.

Then just change the `<server>` element to match where your Erlang server is running and you should be ready. When in doubt, consult the Tsung documentation for explanation of most of the items in `websocket.xml`.
